### ISSUE TITLE
(SOLVED!) No MiniDP audio output with Whatevergreen + Lilu + AppleALC

### ISSUE THREAD

**Issue by Emulle** [Snikii/Lenovo-ThinkPad-T440P#1]
Hello, 

I've used your SSDT-T440P.aml to get.. Well everything working. 
But I am having this issue with the new(?) method of sending audio over HDMI by only using Whatevergreen + Lilu + AppleALC, as per; https://www.tonymacx86.com/threads/applehda-hdmi-audio-guide.234735/ (I have also done a problem reporting on my issue, see post #1000 in this thread if you're interested for debug files and such).
I am running this method because my installation differs from yours, for example I installed Mojave.

I have tried to get your SSDT to work with this method - and also compiled my own but to no avail. 
If you have time I would appreciate if you could take a look at the issue (according to toledo on tonymacosx86): 

> Contact the ssdt developer, problems with:
Method (_SB.PCI0.HDEF._DSM, 4, NotSerialized), hda-gfx injection is not used with HD4600
Method (_SB.PCI0.HDAU._DSM, 4, NotSerialized), not needed with WhateverGreen and AppleALC  
  
Here is my current config.plist and SSDT(which I have customized a bit).

[plistSSDT.zip](https://github.com/Snikii/Lenovo-ThinkPad-T440P/files/2804856/plistSSDT.zip)

Cheers, and thanks for your contribution to get a working Hackintosh on the T440x!   

**SOLVED!**

I recompiled your .dsl files, removed everything IGPU & HDAU/HDEF related and added kexttopatch: 

`AppleIntelFramebufferAzul 01050900 00040000 87000000   -   01051200 00080000 87000000`
`AppleIntelFramebufferAzul 02040900 00040000 87000000  -   02041290 00008000 08700000`

I've yet to been able to patch in battery status in my recompiled .aml but I will upload it & my config.plist when I've managed - for future reference and in case anyone else end up with the same problem. 

[plistSSDT.zip](https://github.com/Snikii/Lenovo-ThinkPad-T440P/files/2810246/plistSSDT.zip)
It's a bit messy and audio doesn't return after sleep anymore, if you end up with the same error your best bet would be to compare your own plist & SSDT and add/extract the needed items.

**Comment by Snikii** [comment]
Guide has become outdated for a while since i had no time to update it, it will be updated soon as many things have changed and i will update everything accordingly, thanks.

Closing.
